### PR TITLE
Furo doc theme

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Doesn't seem to build: https://readthedocs.org/projects/logpyle/builds/12475853/

**Comment by inducer** [comment]
It seems like it's not paying attention to the `.rtd-env.yml`. Any idea why?

**Comment by matthiasdiener** [comment]
> It seems like it's not paying attention to the `.rtd-env.yml`. Any idea why?

Needs to be enabled in the config: https://github.com/illinois-ceesd/mirgecom/blob/master/.readthedocs.yml

**Comment by matthiasdiener** [comment]
Builds now: https://logpyle.readthedocs.io/en/furo-doc-theme/index.html

**Review by matthiasdiener — APPROVED** [review]
This theme looks great!

**Comment by inducer** [comment]
> Builds now

Thanks!

**Pull request merged**
